name: "🐛 Bug"
description: "Reportar un error encontrado"
labels: ["bug"]
body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción del bug
    validations:
      required: true
  - type: textarea
    id: reproducir
    attributes:
      label: Pasos para reproducir
      value: |
        1. 
        2. 
        3. 
  - type: textarea
    id: esperado
    attributes:
      label: Comportamiento esperado
  - type: textarea
    id: actual
    attributes:
      label: Comportamiento actual
  - type: dropdown
    id: prioridad
    attributes:
      label: Prioridad
      options:
        - Crítica
        - Alta
        - Media
        - Baja
